# Configure Using Gemfile
# gem 'pg'
#
default: &default
  adapter: postgresql
  encoding: utf-8
  pool: 5
  username: postgres
  password: postgres
  port: 5432
  host: localhost

development:
  <<: *default
  database: portal_villa_treviso_development
  schema_search_path: adm_portal_villa_treviso

test:
  <<: *default
  database: portal_villa_treviso_test
